version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/text2num

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          # Don't do `python setup.py install` here!
          name: install inplace with dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install sphinx
            python setup.py develop

      - save_cache:
          paths:
            - ./venv

          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test

      # Build the documentation
      - run:
          name: build doc
          command: |
            . venv/bin/activate
            cd doc && make html

      - store_artifacts:
          path: doc/_build/html/
          destination: html-doc

  deploy:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/text2num

    steps:
      - checkout

      - run:
          name: verify git tag vs. version
          command: |
            python setup.py verify

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = allomedia" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            python setup.py sdist

      - run:
          name: upload to pypi
          command: |
            pip install twine
            twine upload dist/*


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release
